- id: '1638458177359'
  alias: Turn off christmas
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
    id: turn-off-christmas
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: group.christmas_lights
  mode: single
- id: '1638541493335'
  alias: turn on christmas
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: homeassistant.turn_on
    target:
      entity_id: group.christmas_lights
  mode: single
