christmas_lights:
    name: Christmas Lights
    entities:
        - switch.wyze_plug_alpha
        - switch.wyze_plug_alpha_2
        - switch.tasmota
        - switch.sonoff_s31_lite_2
        - switch.sonoff_s31_lite_3
