announce_that_christmas_has_begun:
  sequence:
  - service: homeassistant.turn_on
    target:
      entity_id: group.christmas_lights
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speakers
      message: Prepare yourselves, Christmas is Here!
  mode: single
  alias: Announce that Christmas Has Begun
